modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
[[mods]]
modId="stoneutilities"
version="${file.jarVersion}"
displayName="Stone Utilities"
description='''
Remake from Stone Block Utilities
'''
