modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
[[mods]]
modId="stoneutilities"
version="${file.jarVersion}"
displayName="Stone Utilities"
description='''
Stone Utilities with stone tools
'''
